### ISSUE TITLE
How do you get "avg_list"?

### ISSUE THREAD

**Issue by Bonsen** [linhj184169280/CAMELYON16-Challenge#1]
in CorrTxtMaker.py:
avg_list = [[135,85,164],[155,100,135],[165,125,151],[187,155,180],[188,130,160],[145,88,122],[110,75,115],[67,28,120],[100,47,140],[100, 64, 110]]

**Comment by linhj184169280** [comment]
I had analysed the color distribution of tissues from the patches selected from the WSIs. By observation, I found that most color of tissue distributed around the values mentioned in the avg_list.

**Comment by Bonsen** [comment]
thanks.
