### ISSUE TITLE
What does the avg_list in function TxtMake in CorrTxtMaker.py do?

### ISSUE THREAD

**Issue by 842974287** [linhj184169280/CAMELYON16-Challenge#6]
https://github.com/linhj184169280/CAMELYON16-Challenge/blob/925a394d4f7061c33dc8fb94537c28e0a8d62db3/Camelyon2016_Release/Program/Camelyon_VGGRes/Train/CorrTxtMaker.py#L68

学长好,

I have read the code but got confused about this variable "avg_list". Can you explain where it comes from and what does it do please?

**Comment by SCP-173-cool** [comment]
The RGB list of  Effective area from slides, such as  pink or purple.

**Comment by li10141110** [comment]
@842974287 hi,could you please show us the code for generating mask tif files by ASAP.I only got binary files. Following is my code:
import multiresolutionimageinterface as mir
reader = mir.MultiResolutionImageReader()
output_path = '/home/imdl/projects/camelyon17_type_mask_false'
mr_image = reader.open('/home/imdl/projects/Camelyon16/training/tumor/tumor_100.tif')
annotation_list = mir.AnnotationList()
xml_repository = mir.XmlRepository(annotation_list)
xml_repository.setSource('/home/imdl/projects/Camelyon16/training/lesion_annotations/tumor_100.xml')
xml_repository.load()
annotation_mask = mir.AnnotationToMask()
camelyon17_type_mask = False
label_map = {'metastases': 1, 'normal': 2} if camelyon17_type_mask else {'_0': 1, '_1': 1, '_2': 0}
conversion_order = ['metastases', 'normal'] if camelyon17_type_mask else  ['_0', '_1', '_2']
annotation_mask.convert(annotation_list, output_path, mr_image.getDimensions(), mr_image.getSpacing(), label_map, conversion_order)
need help~~
